### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by yuki4ghub15** [ICEBERG-VICOROB/vicorob_DBT_Challenge#1]
Hello, Its a great work!. Could you upload package requirements with version. Thank you.

**Comment by rmartimarly** [comment]
Hi, uploaded requirements.  Enjoy.

**Comment by yuki4ghub15** [comment]
Hi thank you for the env, 
I am struggling for some days here while working with this repository,  could you took into the matter if you can support the env,
I used your env setting. however, when I install omidb==0.7.0,   dcmread_image() from duke-dbt-data.py does not load .dcm input images, because  omidb==0.7.0 install pydicom 1.4.2 version. If I install pydicom == 2.1.1,  its loaded .dcm input images successfully. Note that original repo. of  duke-dbt-data.py says its run on pydicom == 2.1.1. and omidb.mark.boundingbox() does not work on pydicom2.1.1. 
This is happening for running inference_DBT, Thanks.

**Comment by rmartimarly** [comment]
Hello, I've checked and I am usign pydicom 1.4.2 in my environment. Check duke-dbt-data.py from my repo (I think I slightly modified something for loading dicom images correctly).
Best 
Robert.
